import assert from 'node:assert/strict';
import fs from 'node:fs';
const K=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(new URL('../calculs.js',import.meta.url),'utf8')).toString('base64'));
const c={id:'c',j:0,d:'09:00',f:'10:00',sem:'TOUTES',cls:['TEST']};
const C={off:()=>false,parite:()=> 'A',coursSemaine:()=>true};
const a={id:'test',sigle:'TEST',actif:true,filieres:{MELEC:{h:25}},equipes:{PSR_MELEC:1},heures:{PSR_MELEC:25},contrat:25};
const x={C,edt:{cours:{c},classes:{TEST:{pfmp:[]}}},I:{aesh:new Map([['test',a]]),places:[],absences:[],reunions:[]}};
const d='2026-09-21',b={nb:1,plageDebut:'09:00',plageFin:'10:00'};
assert.equal(K.etatBesoin(x,c,d,null),'inconnu');
assert.equal(K.etatBesoin(x,c,d,{...b,nb:0}),'zero');
assert.equal(K.etatBesoin(x,c,d,b),'vide');
x.I.places.push({id:'p',type:'place',statut:'active',aeshId:'test',coursId:'c',jour:0,pole:'PSR_MELEC',du:d,au:d,debut:'09:15',fin:'09:30',semaines:'AB'});
assert.equal(K.etatBesoin(x,c,d,b),'partiel');
x.I.places[0].debut='09:00';x.I.places[0].fin='10:00';
assert.equal(K.etatBesoin(x,c,d,b),'plein');
assert.equal(K.etatBesoin(x,c,d,{...b,nb:2}),'partiel');
x.I.absences.push({aeshId:'test',du:d,au:d,journee:false,debut:'09:15',fin:'09:30'});
assert.equal(K.etatBesoin(x,c,d,b),'partiel');
assert.deepEqual(K.reunionDe(a),{jour:0,debut:'13:00',fin:'14:00'});
let r=K.reunionsEffectives(x,'test',d);assert.equal(r.length,1);assert.equal(r[0].debut,'13:00');
x.I.reunions.push({id:'r',date:d,debut:'08:30',fin:'09:30'});
r=K.reunionsEffectives(x,'test',d);assert.equal(r.length,1);assert.equal(r[0].type,'institution');assert.equal(K.duree(r[0].debut,r[0].fin),1);
x.I.reunions=[];assert.equal(K.reunionsEffectives(x,'test',d)[0].debut,'13:00');
console.log('Indicateurs : cinq états, présence partielle de 15 min, absences ; réunion MELEC et remplacement institutionnel vérifiés.');
