import assert from 'node:assert/strict';
import * as K from '../calculs.js';
import {horsPresence,resumeExterne} from '../services-visuels.mjs';
for(const type of ['reunion','institution'])assert(horsPresence({type,label:'Réunion'},K));
assert(horsPresence({type:'service',label:'PIAL'},K));
for(const label of ['DAFI','Cantine','Internat'])assert(!horsPresence({type:'service',label},K));
const occupation=(label,debut,fin,extra={})=>({type:'service',label,debut,fin,...extra});
const fake={...K,occupations:(_,id,l)=>l==='A'?[occupation('DAFI','09:00','12:00'),occupation('PIAL','13:00','16:00'),occupation('Cantine','12:00','13:00'),{type:'reunion',debut:'08:00',fin:'09:00'}]:[occupation('DAFI','09:00','12:00',{partiel:1}),occupation('PIAL','13:00','16:00',{absent:true})]};
assert.deepEqual(resumeExterne(fake,{}, {id:'test'},[['A','A'],['B','B']]),[{nom:'DAFI',eleves:true,heures:{A:3,B:2}},{nom:'PIAL',eleves:false,heures:{A:3}}]);
console.log('PASS réunions/PIAL neutres, DAFI/DP/internat présence élèves, récapitulatif A/B sans DP ni réunion, absences déduites');
