import assert from 'node:assert/strict';
import fs from 'node:fs';
const uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const kURI=uri(fs.readFileSync(new URL('../calculs.js',import.meta.url),'utf8'));
const dURI=uri(fs.readFileSync(new URL('../donnees.js',import.meta.url),'utf8'));
const K=await import(kURI);
assert.equal(K.fmtH(2.25),'2,25 h','Les quarts d’heure restent précis à l’affichage');
const V=await import(uri(fs.readFileSync(new URL('../verification.js',import.meta.url),'utf8').replace('./calculs.js?v=2026-09-24f',kURI).replace('./donnees.js?v=2026-09-24b',dURI)));
const {enregistrerPlanning}=await import(uri(fs.readFileSync(new URL('../enregistrement.js',import.meta.url),'utf8')));
const du=K.ajoute(K.lundiDe(K.isoLocal()),7),au=K.ajoute(du,11);
const c={id:'test',lib:'Cours fictif',j:0,d:'09:00',f:'11:00',sem:'TOUTES',cls:['C1PSR']};
const autre={...c,id:'autre',cls:['B1MELEC']};
const edt={cours:{test:c,autre},classes:{C1PSR:{pole:'PSR_MELEC',pfmp:[]},B1MELEC:{pole:'PSR_MELEC',pfmp:[]}}};
const C=K.creerCalendrier({semaine1:du,vacances:[]});
const a={id:'aesh_d01',type:'aesh',sigle:'TEST',actif:true,contrat:35,equipes:{PSR_MELEC:1},heures:{PSR_MELEC:35},services:[],reunion:{jour:0,debut:'13:00',fin:'14:00'},version:1};
const old={id:'place_oldtest',type:'place',aeshId:a.id,coursId:c.id,classes:c.cls,jour:0,debut:'09:00',fin:'11:00',semaines:'AB',du:K.ajoute(du,-14),au:K.ajoute(au,14),statut:'active',pole:'PSR_MELEC'};
const data={du,au,valides:[0,1,2,3,4,5,6,7,8,9],internat:false,dpConfirmee:true,lignes:[{jour:0,semaine:'A',cible:'test',debut:'09:30',fin:'10:00'},{jour:1,semaine:'B',cible:'service:Cantine',debut:'12:30',fin:'13:00'}]};
let draft={id:'verification_d01_20262027',type:'verification',aeshId:a.id,contenu:JSON.stringify(data),statut:'brouillon'};
const base=new Map([[a.id,a],[old.id,old],[draft.id,draft]]);
const context=()=>({edt,C,I:K.indexer([...base.values()],[],['PSR_MELEC'],[]),nomPole:()=> 'Test'});
let n=0;const params=()=>({draft,base,ctx:context(),nouvelId:()=>String(++n).padStart(10,'0')});
const plan=V.preparerValidation(params());
assert.equal(plan.lot.find(d=>d.id===old.id).statut,'retire');
assert(plan.lot.some(d=>d.type==='place'&&d.au===K.ajoute(du,-1)));
assert(plan.lot.some(d=>d.type==='place'&&d.du===K.ajoute(au,1)));
const present=plan.lot.filter(d=>d.type==='place'&&d.du===du&&d.au===au);
assert.equal(present.length,1);assert.equal(present[0].semaines,'A');assert.equal(present[0].debut,'09:30');
assert.equal(plan.bilans.find(b=>b.sem==='B').total,1.5,'DP de 30 min + réunion de 1 h');
const simulation={...context(),I:K.indexer(plan.lot.filter(d=>d.type!=='place').concat(present),[],['PSR_MELEC'],[])};
assert.equal(K.bilan(simulation,a.id,K.ajoute(du,-7)).services,0,'Pas de forfait inventé avant le début du service');
const updated=plan.lot.find(d=>d.type==='aesh');assert.deepEqual(updated.reunion,a.reunion);assert.equal(updated.services[0].horaires[0].semaines,'B');
assert.throws(()=>V.verifierLigne({...data.lignes[0],fin:'12:00'},edt),/présence/);
assert.throws(()=>V.verifierLigne({...data.lignes[0],cible:''},edt),/Choisissez/);
draft={...draft,contenu:JSON.stringify({...data,valides:[]})};assert.throws(()=>V.preparerValidation(params()),/Vérifiez les deux/);
draft=base.get(draft.id);
const conflict={...old,id:'place_conflict',coursId:'autre',classes:autre.cls};base.set(conflict.id,conflict);
assert.throws(()=>V.preparerValidation(params()),/Conflit/);base.delete(conflict.id);
const store=new Map(base),history=new Map();
const FS={doc:(_,col,id)=>({col,id}),runTransaction:async(_,fn)=>{const ops=[];const r=await fn({get:async ref=>({exists:()=>store.has(ref.id),data:()=>store.get(ref.id)}),set:(ref,d)=>ops.push([ref,d])});for(const [ref,d]of ops)(ref.col==='hist'?history:store).set(ref.id,d);return r;}};
const write=()=>enregistrerPlanning({FS,db:{},collection:'main',historique:'hist',docs:plan.lot,base,annee:'2026-2027',par:'PSR_MELEC',nouvelId:()=>String(++n).padStart(10,'0'),maintenant:'test'});
store.set(a.id,{...a,version:2});await assert.rejects(write(),e=>e.code==='conflit');assert.equal(history.size,0);assert.equal(store.get(old.id).statut,'active');
store.set(a.id,a);await write();assert.equal(store.get(draft.id).statut,'valide');assert.equal(store.get(a.id).revisionPlanning,1);assert(history.size>0);
await assert.rejects(write(),e=>e.code==='conflit');
console.log('Vérification : A/B, fractionnement, passé/futur préservés, réunions intactes, DP B, cours invalide, contrôle incomplet, conflits, transaction atomique, concurrence et double validation vérifiés.');
