/* Parcours de mobilisation complémentaire. Aucun changement des demandes d'épreuves existantes. */
const escapeHTML = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const texte = (v,n=120) => String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);
export function estimation(classes, documents) {
 const uniques=[...new Set(classes)];let total=0;const manquantes=[];
 for(const k of uniques){const n=documents[k]?.effectif;if(Number.isInteger(n)&&n>=0)total+=n;else manquantes.push(k);}
 return {total,manquantes,classes:uniques};
}
export function verifierSortie(f){
 const e=[];if(!texte(f.auteur,60))e.push('Indiquez la matière ou votre prénom.');if(!texte(f.objet))e.push('Indiquez l’objet.');
 if(!f.classes.length&&!texte(f.autreClasse,60))e.push('Choisissez au moins une classe ou précisez un groupe.');
 const dateTest=new Date(f.date+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(f.date)||!Number.isFinite(dateTest.getTime())||dateTest.toISOString().slice(0,10)!==f.date)e.push('Choisissez une date valide.');
 if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(f.debut)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(f.fin)||f.fin<=f.debut)e.push('Vérifiez les horaires de départ et de retour.');
 if(!texte(f.lieu))e.push('Précisez le lieu.');
 for(const [k,label] of [['effectif','élèves'],['enseignants','enseignants'],['adultes','autres adultes'],['aesh','AESH souhaitées']])if(f[k]!==''&&(!/^\d+$/.test(String(f[k]))||+f[k]>10000))e.push('Vérifiez le nombre de '+label+'.');
 if(f.aesh==='')e.push('Indiquez le nombre d’AESH souhaitées.');return e;
}
export function construireSortie(f,{id,annee,classes,documents,now=new Date().toISOString()}){
 const ids=[...new Set(f.classes)],lib=ids.map(k=>classes[k]?.court||k).concat(texte(f.autreClasse,60)||[]).join(' + '),nb=Number(f.aesh),est=estimation(ids,documents);
 const groupe=ids.join('+')||'autre';
 return {id,type:'epreuve',annee,matiere:texte(f.auteur,60),nature:f.motif==='autre'?'autre':'sortie',natureAutre:f.motif==='autre'?'Accompagnement':'',forme:'',formeAutre:'',intitule:texte(f.objet),
 classes:[{classe:groupe,classes:ids,libelle:lib,autre:!!texte(f.autreClasse,60),intitule:texte(f.objet),diplome:'',pole:classes[ids[0]]?.pole||'',nbSouhaite:nb,comptes:{effectifEstime:est.manquantes.length?null:est.total,effectifPrevu:f.effectif===''?null:+f.effectif}}],
 seances:[{classe:groupe,libelle:lib,intitule:texte(f.objet),date:f.date,debut:f.debut,fin:f.fin,duree:(+f.fin.slice(0,2)*60+ +f.fin.slice(3))-(+f.debut.slice(0,2)*60+ +f.debut.slice(3)),tiersTemps:false,salle:texte(f.lieu,120),nbAesh:nb,nbPropose:0,dejaPresentes:null,renfort:nb,mobilisation:true,transport:texte(f.transport,80),transportAutre:texte(f.transportAutre,80),enseignants:f.enseignants===''?null:+f.enseignants,autresAdultes:f.adultes===''?null:+f.adultes,effectifPrevu:f.effectif===''?null:+f.effectif}],
 observations:texte(f.notes,600),autreDemande:'',statut:'nouvelle',reponse:{statut:'',texte:'',majLe:''},creeLe:now,majLe:now,source:'epreuves-aesh'};
}
export function installerSorties(api){
 const titre=document.getElementById('titre'),vue=document.getElementById('vue'),intro=titre.parentElement.querySelector('p');
 const nav=document.createElement('div');nav.className='mobilisation-nav';nav.innerHTML='<button type="button" data-motif="epreuve" aria-pressed="true">Épreuve / CCF</button><button type="button" data-motif="sortie" aria-pressed="false">Sortie</button><button type="button" data-motif="autre" aria-pressed="false">Autre besoin</button>';titre.parentElement.append(nav);
 const panel=document.createElement('main');panel.id='mobilisation-sortie';panel.hidden=true;vue.after(panel);
 const style=document.createElement('style');style.textContent=`.mobilisation-nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.mobilisation-nav button{padding:10px 14px;border-radius:9px;border:1px solid #b9c4d3;background:#fff;color:#172336;font:inherit}.mobilisation-nav button[aria-pressed=true]{background:#166548;color:#fff;border-color:#166548}#mobilisation-sortie{max-width:850px;margin:24px auto;padding:0 16px 30px}#mobilisation-sortie *{box-sizing:border-box}#mobilisation-sortie section{background:#fff;border:1px solid #ccd6dc;border-radius:14px;padding:20px;margin:16px 0}#mobilisation-sortie .grille{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}#mobilisation-sortie label{display:grid;gap:6px;color:#243544}#mobilisation-sortie input,#mobilisation-sortie select,#mobilisation-sortie textarea{font:inherit;min-width:0;width:100%;padding:11px;border:1px solid #aab9c6;border-radius:8px;background:#fff;color:#172336}#mobilisation-sortie input[type=checkbox]{width:18px;height:18px;accent-color:#166548}#mobilisation-sortie .case{display:flex;gap:8px;align-items:center;padding:9px;background:#f3f6f8;border-radius:7px}#mobilisation-sortie .estimation{padding:12px;margin:14px 0;background:#edf6f1;color:#224535;border-radius:9px}#mobilisation-sortie button{font:inherit;padding:10px 14px;border:1px solid #bac8d0;border-radius:9px;background:#fff;color:#172336}#mobilisation-sortie .principal{background:#166548;color:#fff;border:0}#mobilisation-sortie .actions{display:flex;gap:10px;flex-wrap:wrap;justify-content:space-between;margin-top:16px}#mobilisation-sortie h2{font-size:1.1rem;margin:0 0 14px}#mobilisation-sortie small{color:#4c6071}#mobilisation-sortie details{margin:12px 0}#mobilisation-sortie [hidden]{display:none!important}@media(max-width:540px){#mobilisation-sortie .grille{grid-template-columns:1fr}}`;document.head.append(style);
 const key=api.cleBrouillon||'coordination-mobilisation-brouillon-v1';const docs={},loading=new Set();let mode='epreuve',pending=null,sending=false;
 let f={motif:'sortie',auteur:'',objet:'',classes:[],autreClasse:'',date:'',debut:'',fin:'',lieu:'',transport:'',transportAutre:'',enseignants:'',adultes:'',effectif:'',effectifManuel:false,aesh:'',notes:''};
 try{const b=JSON.parse(localStorage.getItem(key)||'null');if(b?.form?.classes&&Array.isArray(b.form.classes)){f={...f,...b.form};pending=b.pending||null;}}catch(_){}
 const save=()=>{try{localStorage.setItem(key,JSON.stringify({form:f,pending}));}catch(_){}};
 function actualiser(){const e=estimation(f.classes,docs);if(!f.effectifManuel)f.effectif=e.manquantes.length||f.autreClasse?'':String(e.total);const el=panel.querySelector('[data-estimation]');if(el)el.textContent=e.manquantes.length?'Estimation en attente pour '+e.manquantes.length+' classe(s) · effectifs connus : '+e.total:'Estimation du nombre d’élèves prévus : '+e.total+(f.autreClasse?' + groupe à préciser':'');const n=panel.querySelector('[name=effectif]');if(n)n.value=f.effectif;}
 async function charger(k){if(loading.has(k)||Object.hasOwn(docs,k))return;loading.add(k);try{docs[k]=await api.effectif(k);}catch(_){docs[k]=null;}finally{loading.delete(k);actualiser();save();}}
 function render(){const edt=api.edt();const classes=edt?.classes||{};const input=(name,label,type='text',max=120)=>`<label>${label}<input name="${name}" ${name==='auteur'?'list="sortie-matieres"':''} type="${type}" ${type==='number'?'min="0" max="10000"':`maxlength="${max}"`} value="${escapeHTML(f[name])}"></label>`;
 const champs=()=>`<section><div class="grille">${input('auteur','Matière ou prénom de l’enseignant','text',60)}${input('objet','Objet')}</div><datalist id="sortie-matieres">${[...new Set(Object.values(edt?.cours||{}).map(c=>c.lib).filter(Boolean))].sort().map(m=>`<option value="${escapeHTML(m)}"></option>`).join('')}</datalist></section><section><h2>Classes concernées</h2><div class="grille">${api.choix.filter(l=>l.every(k=>classes[k])).map(l=>{const checked=l.every(k=>f.classes.includes(k));return `<label class="case"><input type="checkbox" data-cls="${l.join('+')}" ${checked?'checked':''}>${escapeHTML(l.map(k=>classes[k].court||k).join(' + '))}</label>`;}).join('')}</div><details ${f.autreClasse?'open':''}><summary>Autre classe ou groupe</summary>${input('autreClasse','Classe / groupe à préciser','text',60)}</details><p class="estimation" data-estimation aria-live="polite"></p><div class="grille">${input('effectif','Nombre d’élèves prévu · modifiable','number')}${input('enseignants','Nombre d’enseignants accompagnateurs','number')}${input('adultes','Nombre d’autres adultes','number')}${input('aesh','Nombre d’AESH souhaitées au total','number')}</div><small>Vous pouvez corriger le nombre d’élèves ou le laisser à préciser.</small><button type="button" data-reset>Reprendre l’estimation</button></section><section><h2>Date et organisation</h2><div class="grille">${input('date','Date','date')}${input('lieu','Destination / lieu')}${input('debut','Départ','time')}${input('fin','Retour','time')}<label>Mode de transport<select name="transport">${['','À pied','Transports en commun · bus, métro, tram','Autocar','Autre'].map(t=>`<option value="${escapeHTML(t)}" ${t===f.transport?'selected':''}>${escapeHTML(t||'À préciser')}</option>`).join('')}</select></label>${input('transportAutre','Précision sur le transport · facultatif','text',80)}</div><label style="margin-top:14px">Informations complémentaires<textarea name="notes" rows="3" maxlength="600" placeholder="Organisation, repas, rendez-vous… Aucun nom d’élève.">${escapeHTML(f.notes)}</textarea></label></section><div class="actions"><button type="button" data-save>Garder en préparation</button><button type="submit" class="principal">Vérifier la demande →</button></div>`;
 panel.innerHTML=`<form>${champs()}</form><p data-message role="status" aria-live="polite"></p>`;actualiser();f.classes.forEach(charger);
 }
 function choisir(m){if(sending)return;mode=m;nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.motif===mode)));vue.hidden=m!=='epreuve';panel.hidden=m==='epreuve';titre.textContent=m==='epreuve'?'Besoin AESH pour une épreuve':m==='sortie'?'Demander des AESH pour une sortie':'Demander un accompagnement AESH';intro.textContent=m==='epreuve'?'CCF, CCF blanc, bac blanc, évaluation : préparez votre demande.':'Indiquez les classes, les horaires et le nombre d’AESH souhaitées.';if(m!=='epreuve'){if(f.motif!==m)pending=null;f.motif=m;render();}}
 nav.onclick=e=>{const b=e.target.closest('[data-motif]');if(b)choisir(b.dataset.motif);};
 panel.oninput=e=>{if(!e.target.name)return;pending=null;f[e.target.name]=e.target.value;if(e.target.name==='effectif')f.effectifManuel=true;if(e.target.name==='autreClasse')actualiser();save();};
 panel.onchange=e=>{const ids=e.target.dataset.cls?.split('+');if(!ids)return;pending=null;f.classes=e.target.checked?[...new Set([...f.classes,...ids])]:f.classes.filter(k=>!ids.includes(k));save();render();};
 function message(t){panel.querySelector('[data-message]').textContent=t;}
 panel.onclick=e=>{if(e.target.closest('[data-save]')){save();message('Préparation conservée sur cet appareil. Aucun envoi.');}if(e.target.closest('[data-reset]')){f.effectifManuel=false;actualiser();save();}if(e.target.closest('[data-back]'))render();if(e.target.closest('[data-send]'))envoyer();};
 panel.onsubmit=e=>{e.preventDefault();const err=verifierSortie(f);if(err.length){message(err.join(' '));return;}if(!pending)pending=construireSortie(f,{id:api.id(),annee:api.annee,classes:api.edt().classes,documents:docs});save();const s=pending.seances[0];panel.innerHTML=`<section><h2>Vérifier la demande</h2><p><b>${escapeHTML(pending.intitule)}</b> · ${escapeHTML(pending.matiere)}</p><p>${escapeHTML(s.libelle)}</p><p>${escapeHTML(s.date)} · ${escapeHTML(s.debut)}–${escapeHTML(s.fin)} · ${escapeHTML(s.salle)}</p><p>${s.effectifPrevu??'À préciser'} élèves · ${s.enseignants??'À préciser'} enseignant(s) · ${s.autresAdultes??'À préciser'} autre(s) adulte(s)</p><p>${s.nbAesh} AESH souhaitée(s) au total</p><p>${escapeHTML(s.transport)} ${escapeHTML(s.transportAutre)}</p><p>${escapeHTML(pending.observations)}</p><div class="actions"><button type="button" data-back>Modifier</button><button type="button" data-send class="principal">Transmettre au référent</button></div></section><p data-message role="status" aria-live="polite"></p>`;};
 async function envoyer(){if(sending||!pending)return;sending=true;const button=panel.querySelector('[data-send]');button.disabled=true;message('Envoi en cours…');try{await api.envoyer(pending);localStorage.removeItem(key);f={...f,classes:[],auteur:'',objet:'',autreClasse:'',date:'',debut:'',fin:'',lieu:'',enseignants:'',adultes:'',effectif:'',effectifManuel:false,aesh:'',notes:''};panel.innerHTML='<section role="status"><h2>Demande transmise</h2><p>Le référent peut maintenant organiser l’accompagnement. Les affectations AESH restent à confirmer.</p></section>';pending=null;}catch(_){message('Envoi non confirmé. Votre préparation est conservée. Vous pouvez réessayer sans créer une seconde demande.');button.disabled=false;}finally{sending=false;}}
 return {choisir};
}
